version: '3'
services:
  snx-vpn:
    image: kedu/snx-checkpoint-vpn
    container_name: snx-vpn
    cap_add:
      - ALL
    volumes:
      - /lib/modules:/lib/modules
      - /etc/modules:/etc/modules
    environment:
      - SNX_SERVER=go.ua.pt
      - SNX_USER=gilteixeira@ua.pt
      - SNX_PASSWORD=suckOnThisNuts
    restart: unless-stopped
  nodejs-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: your_nodejs_api_image
    container_name: nodejs-api
    restart: unless-stopped
    environment:
      - DB_HOST=your_db_host
      - DB_PORT=your_db_port
      - DB_USER=your_db_user
      - DB_PASSWORD=your_db_password
    ports:
      - "3000:3000" # Adjust this according to your API's port
    volumes:
      - .:/app
    working_dir: /app
    network_mode: service:snx-vpn
    depends_on:
      - snx-vpn