version: '3'
services:
  snx-vpn:
    image: vpn_image:latest
    container_name: snx-vpn
    cap_add:
      - ALL
    volumes:
      - /lib/modules:/lib/modules
      - /etc:/etc_host
    environment:
      - SNX_SERVER=go.ua.pt
      - SNX_USER=gilteixeira@ua.pt
      - SNX_PASSWORD=suckOnThis
    restart: unless-stopped
  nodejs-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api_image:latest
    container_name: nodejs-api
    restart: unless-stopped
    environment:
      - DB_HOST=your_db_host
      - DB_PORT=your_db_port
      - DB_USER=your_db_user
      - DB_PASSWORD=your_db_password
    volumes:
      - .:/app
    working_dir: /app
    network_mode: service:snx-vpn
    depends_on:
      - snx-vpn
